### ISSUE TITLE
Display issue when expanding 

### ISSUE THREAD

**Issue by sderrick** [TekyaygilFethi/FethiTekyaygil#7]
Open the Demo page with the timeline, with your browser narrowed down.
press "Next" button until timeline shifted fully to the left. No more items to the right.
Then drag the page wider, the "Next" button shifts right but the timeline doesn't. Pressing the "Next" button causes the timline to re-adjust to the wider view and look normal.

**Comment by TekyaygilFethi** [comment]
Thanks for the feedback. The problem is transformX property which can't be responsive at window resize operations. At narrowed window the transform value is as shown below when "Next" button is pressed until there are no more items to shift:
![resim](https://user-images.githubusercontent.com/28951869/76760189-3e8ad100-679e-11ea-9ae7-422ea6c4dd4b.png)
When I expand the window the transform value stays still at -1697px:
![resim](https://user-images.githubusercontent.com/28951869/76760459-c2dd5400-679e-11ea-8063-9bb6fc0d1903.png)
This is the cause of the problem. I'll investigate and fix that problem ASAP.

**Comment by TekyaygilFethi** [comment]
Hello,
Sorry for late response, because of Corona I had to work from home but instead of being more relaxed, all works are increased twice :) 

I've managed the solve the propblem. I was using 3rd party library for timeline component and when I investigate the code I found a method called e which does a transfrom operation to corresponding elements (which in case there, a container that contains the green date dots that does not slide right at screen resize.). All I needed to do trigger that event when window resized. Then I wrote the code below:

    `window.onresize = function (event) {
        var d = document.getElementsByClassName("js-cd-h-timeline");
        e(d[0]);
    };`

At first, I got all corresponding html element with respect to class name. Here, I only have 1 corresponding element to that class name that's why I send it parameter to e function as d[0].
That solved the problem. Thanks for finding issues again :) 👍
